"""pgeo-tune: apply a measured tuning profile to a pgeo deployment (docker compose).

    pgeo-tune list                                  profiles and what they are for
    pgeo-tune apply medium [--no-restart] [-f compose.pinned.yml]
    pgeo-tune auto --cpus 2 --mem-gb 4 [--write]    extrapolate a profile for another machine
    pgeo-tune show                                  active profile and effective settings
    pgeo-tune verify [--url http://127.0.0.1:4700]  known-answer queries through the API(s)

A profile (pgeo/tuning/profiles/<name>.toml) has three parts:
  [machine]   what it was measured on (cpus, database memory, load-test config)
  [postgres]  server settings, rendered to pgeo/docker/db/tuning/active.conf (included by
              postgresql.conf)
  [frontend]  API workers, connection pools, parser, rendered to pgeo/tuning/active.vars
              (passed to docker compose as a second --env-file)

Ranking and search tuning is not here: it lives in pgeo/sql/*.sql and every
`pgeo-load build` (or `pgeo-load functions`) applies it. See docs/TUNING_REPORT.md.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import math
import os
import random
import re
import subprocess
import sys
import time
import tomllib
from pathlib import Path

from pgeo.settings import PGEO_ROOT, SECRETS_FILE, Settings

PROFILES_DIR = PGEO_ROOT / "tuning" / "profiles"
ACTIVE_CONF = PGEO_ROOT / "docker" / "db" / "tuning" / "active.conf"
ACTIVE_VARS = PGEO_ROOT / "tuning" / "active.vars"
COMPOSE = PGEO_ROOT / "compose.yml"
NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,40}$")

# Allowlist: only these server settings may come from a profile, each with a value check.
# Anything else (archive_command, shared_preload_libraries with arbitrary libraries, ...) is
# rejected, so a profile file cannot turn into a way to run code in the database.
SIZE_RE = re.compile(r"^\d{1,6}(kB|MB|GB)$")
PG_KEYS: dict[str, object] = {
    "shared_buffers": SIZE_RE,
    "effective_cache_size": SIZE_RE,
    "work_mem": SIZE_RE,
    "maintenance_work_mem": SIZE_RE,
    "max_connections": range(10, 501),
    "max_parallel_workers_per_gather": range(0, 65),
    "max_parallel_workers": range(0, 257),
    "max_worker_processes": range(1, 257),
    "random_page_cost": (0.1, 10.0),
    "jit": {"on", "off"},
    # the libpostal extension arm (T7) preloads the model once in the postmaster
    "shared_preload_libraries": {"", "postal"},
}
FRONTEND = {
    "api_workers": range(1, 65),
    "api_pool_max": range(1, 101),
    "rest_pool": range(1, 201),
    "parse_mode": {"none", "service", "extension"},
}
UNIT_BYTES = {"B": 1, "kB": 1024, "8kB": 8192, "MB": 1024**2, "GB": 1024**3}


class ProfileError(ValueError):
    pass


def _check(section: str, key: str, value: object, rule: object) -> None:
    ok = False
    if isinstance(rule, re.Pattern):
        ok = isinstance(value, str) and bool(rule.fullmatch(value))
    elif isinstance(rule, range):
        ok = isinstance(value, int) and not isinstance(value, bool) and value in rule
    elif isinstance(rule, tuple):
        ok = isinstance(value, int | float) and not isinstance(value, bool) and rule[0] <= value <= rule[1]
    elif isinstance(rule, set):
        ok = value in rule
    if not ok:
        raise ProfileError(f"[{section}] {key} = {value!r} is not allowed")


def validate(profile: dict) -> dict:
    for section in ("machine", "postgres", "frontend"):
        if not isinstance(profile.get(section), dict):
            raise ProfileError(f"missing [{section}] table")
    for key, value in profile["postgres"].items():
        if key not in PG_KEYS:
            raise ProfileError(f"[postgres] {key} is not a tunable setting (allowed: {', '.join(PG_KEYS)})")
        _check("postgres", key, value, PG_KEYS[key])
    for key, rule in FRONTEND.items():
        if key not in profile["frontend"]:
            raise ProfileError(f"[frontend] {key} missing")
        _check("frontend", key, profile["frontend"][key], rule)
    extra = set(profile["frontend"]) - set(FRONTEND)
    if extra:
        raise ProfileError(f"[frontend] unknown keys: {sorted(extra)}")
    return profile


def load_profile(name: str) -> dict:
    if not NAME_RE.fullmatch(name):
        raise ProfileError(f"invalid profile name {name!r}")
    path = PROFILES_DIR / f"{name}.toml"
    if not path.is_file():
        raise ProfileError(f"no profile {name!r} (have: {', '.join(profile_names())})")
    return validate(tomllib.loads(path.read_text()))


def profile_names() -> list[str]:
    return sorted(p.stem for p in PROFILES_DIR.glob("*.toml"))


def _pg_value(v: object) -> str:
    return f"'{v}'" if isinstance(v, str) else str(v)


def render_conf(name: str, profile: dict) -> str:
    lines = [
        f"# Generated by pgeo-tune from pgeo/tuning/profiles/{name}.toml. Do not edit: change the",
        "# profile and run `pgeo-tune apply` again.",
        f"# {profile['machine'].get('description', '')}",
    ]
    lines += [f"{k} = {_pg_value(v)}" for k, v in profile["postgres"].items()]
    return "\n".join(lines) + "\n"


def render_vars(name: str, profile: dict) -> str:
    fe = profile["frontend"]
    return (
        f"# Generated by pgeo-tune from pgeo/tuning/profiles/{name}.toml (docker compose --env-file).\n"
        f"PGEO_TUNING_PROFILE={name}\n"
        f"PGEO_WORKERS={fe['api_workers']}\n"
        f"PGEO_POOL_MAX={fe['api_pool_max']}\n"
        f"PGEO_REST_POOL={fe['rest_pool']}\n"
        f"PGEO_PARSE_MODE={fe['parse_mode']}\n"
    )


def to_bytes(value: str) -> int:
    m = re.fullmatch(r"(\d+)(kB|MB|GB)", value)
    if not m:
        raise ProfileError(f"not a size: {value!r}")
    return int(m.group(1)) * UNIT_BYTES[m.group(2)]


def human(setting: str, unit: str | None) -> str:
    """pg_settings value with its unit as a readable size ("131072" x 8kB -> "1GB")."""
    if unit not in UNIT_BYTES or not setting.isdigit():
        return setting
    n = int(setting) * UNIT_BYTES[unit]
    for suffix, size in (("GB", 1024**3), ("MB", 1024**2), ("kB", 1024)):
        if n >= size and n % size == 0:
            return f"{n // size}{suffix}"
    return f"{n}B"


def auto_profile(cpus: int, mem_gb: float) -> dict:
    """Extrapolate from the measured profiles (see docs/TUNING_REPORT.md, "Sizing rules").

    Memory left for the database = machine memory - 0.8 GB for the OS - the HTTP front end.
    shared_buffers ~25% of that (the rest is the OS page cache, which PostgreSQL also uses),
    effective_cache_size ~75%, connections = 2 x cpus + 2 (queries are CPU bound)."""
    if cpus < 1 or not 1.0 <= mem_gb <= 1024:
        raise ProfileError("cpus must be >= 1 and mem-gb between 1 and 1024")
    front_gb = 0.25 + 0.1 * cpus  # PostgREST, or uvicorn workers
    db_gb = mem_gb - 0.8 - front_gb
    if db_gb < 0.6:
        raise ProfileError(f"{mem_gb} GB leaves {db_gb:.2f} GB for the database; the smallest tested is 0.6 GB")
    db_mb = int(db_gb * 1024)
    sb = max(128, min(8192, db_mb // 4 // 32 * 32))
    conns = 2 * cpus + 2
    return validate(
        {
            "machine": {
                "description": f"auto: {cpus} vCPU, {mem_gb:g} GB (extrapolated, not load-tested)",
                "cpus": cpus,
                "db_memory_gb": round(db_gb, 2),
                "load_test_config": "",
            },
            "postgres": {
                "shared_buffers": f"{sb}MB",
                "effective_cache_size": f"{db_mb * 3 // 4}MB",
                "work_mem": "8MB" if db_gb < 1.0 else "16MB",
                "max_parallel_workers_per_gather": 0,
                "jit": "off",
            },
            "frontend": {
                "api_workers": cpus,
                "api_pool_max": max(2, math.ceil(conns / cpus)),
                "rest_pool": conns,
                "parse_mode": "none",
            },
        }
    )


def to_toml(profile: dict) -> str:
    out = []
    for section in ("machine", "postgres", "frontend"):
        out.append(f"[{section}]")
        for k, v in profile[section].items():
            out.append(f'{k} = "{v}"' if isinstance(v, str) else f"{k} = {v}")
        out.append("")
    return "\n".join(out)


def compose(extra: list[Path], *args: str) -> None:
    cmd = ["docker", "compose", "--env-file", str(SECRETS_FILE), "--env-file", str(ACTIVE_VARS), "-f", str(COMPOSE)]
    for f in extra:
        cmd += ["-f", str(f)]
    subprocess.run([*cmd, *args], check=True)  # noqa: S603 (fixed argv, no shell)


def wait_healthy(timeout: int = 180) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline:
        r = subprocess.run(  # noqa: S603
            ["docker", "exec", "pgeo_db", "pg_isready", "-U", "pgeo", "-d", "pgeo"],  # noqa: S607
            capture_output=True,
        )
        if r.returncode == 0:
            return
        time.sleep(2)
    raise RuntimeError("database did not become ready")


# Readiness probes for the HTTP front ends started by compose.yml (FastAPI, PostgREST).
READY_URLS = [
    "http://127.0.0.1:4500/v1/search?text=portland&size=1",
    "http://127.0.0.1:4600/rpc/v1_search?text=portland&size=1",
]


def wait_http(urls: list[str], timeout: int = 120) -> None:
    """Block until every front end answers 200 (uvicorn workers start after the database)."""
    import httpx

    deadline = time.time() + timeout
    pending = list(urls)
    while pending and time.time() < deadline:
        for u in list(pending):
            try:
                if httpx.get(u, timeout=5).status_code == 200:
                    pending.remove(u)
            except httpx.HTTPError:
                pass
        if pending:
            time.sleep(2)
    if pending:
        raise RuntimeError(f"front ends not ready after {timeout}s: {pending}")


async def effective(keys: list[str]) -> dict[str, tuple[str, str | None]]:
    import asyncpg

    con = await asyncpg.connect(Settings.load().dsn, timeout=30)
    try:
        rows = await con.fetch("SELECT name, setting, unit FROM pg_settings WHERE name = ANY($1::text[])", keys)
        return {r["name"]: (r["setting"], r["unit"]) for r in rows}
    finally:
        await con.close()


def mismatches(profile: dict, eff: dict[str, tuple[str, str | None]]) -> list[str]:
    bad = []
    for key, want in profile["postgres"].items():
        setting, unit = eff.get(key, ("?", None))
        if isinstance(want, str) and SIZE_RE.fullmatch(want):
            got = int(setting) * UNIT_BYTES.get(unit or "B", 1) if setting.isdigit() else -1
            ok = got == to_bytes(want)
        elif isinstance(want, float):
            ok = math.isclose(float(setting), want)
        else:
            ok = str(setting) == str(want)
        if not ok:
            bad.append(f"{key}: want {want}, database has {setting}{unit or ''}")
    return bad


def cmd_list(_: argparse.Namespace) -> int:
    for name in profile_names():
        p = load_profile(name)
        m, pg, fe = p["machine"], p["postgres"], p["frontend"]
        print(
            f"{name:12} {m.get('description', '')}\n{'':12} shared_buffers={pg.get('shared_buffers')} "
            f"effective_cache_size={pg.get('effective_cache_size')} work_mem={pg.get('work_mem')} "
            f"api_workers={fe['api_workers']} rest_pool={fe['rest_pool']} parser={fe['parse_mode']}"
        )
    return 0


def cmd_apply(args: argparse.Namespace) -> int:
    profile = load_profile(args.profile)
    ACTIVE_CONF.write_text(render_conf(args.profile, profile))
    ACTIVE_VARS.write_text(render_vars(args.profile, profile))
    print(f"wrote {ACTIVE_CONF.relative_to(PGEO_ROOT.parent)} and {ACTIVE_VARS.relative_to(PGEO_ROOT.parent)}")
    if args.no_restart:
        print("not restarted: run `pgeo-tune apply` without --no-restart (or recreate db, api, rest) to take effect")
        return 0
    # shared_buffers needs a server restart; the front ends read their env at start
    compose(args.file, "up", "-d", "--force-recreate", "db", "api", "rest")
    wait_healthy()
    wait_http(READY_URLS)
    bad = mismatches(profile, asyncio.run(effective(list(profile["postgres"]))))
    for b in bad:
        print("MISMATCH", b)
    print("applied" if not bad else "settings did not take effect", args.profile)
    return 1 if bad else 0


def cmd_auto(args: argparse.Namespace) -> int:
    profile = auto_profile(args.cpus, args.mem_gb)
    text = f"# Extrapolated by pgeo-tune auto --cpus {args.cpus} --mem-gb {args.mem_gb:g}\n" + to_toml(profile)
    if args.write:
        path = PROFILES_DIR / "auto.toml"
        path.write_text(text)
        print(f"wrote {path.relative_to(PGEO_ROOT.parent)}; apply with: pgeo-tune apply auto")
    else:
        print(text)
    return 0


def cmd_show(_: argparse.Namespace) -> int:
    active = "none (base postgresql.conf only)"
    if ACTIVE_VARS.is_file():
        m = re.search(r"^PGEO_TUNING_PROFILE=(\S+)$", ACTIVE_VARS.read_text(), re.M)
        active = m.group(1) if m else "unknown"
    print("active profile:", active)
    for name, (setting, unit) in sorted(asyncio.run(effective(list(PG_KEYS))).items()):
        print(f"  {name:34} {human(setting, unit)}")
    return 0


# Known answers that exercise each tuned path (all found in docs/PGEO_TUNING.md).
# Known answers live per build in pgeo/tuning/verify/<build>.json, because they are facts about
# a region, not about the engine: "Portland, Maine" is a Maine fact and says nothing about a New
# York build. A build with no file of its own has nothing to check, and says so rather than
# passing silently.
VERIFY_DIR = PGEO_ROOT / "tuning" / "verify"


def verify_cases(build: str) -> list[tuple[str, dict, str, str | None]]:
    path = VERIFY_DIR / f"{build}.json"
    if not path.exists():
        raise SystemExit(
            f"no known answers for build {build!r}: write {path.relative_to(PGEO_ROOT.parent)} "
            f"(see me.json) with queries whose right answer is a fact about the region"
        )
    doc = json.loads(path.read_text())
    # "layer" is optional, and wanted on any case whose answer is a place. The label alone cannot
    # tell the city of Albany from Albany County or from a shop called "Albany, NY - Albany.com":
    # "Albany" is in all three, so a substring test passes all three. Two real New York failures
    # hid behind exactly that until 2026-09-23.
    return [(c["path"], c["params"], c["want"], c.get("layer")) for c in doc["cases"]]



# The accuracy case sets double as the contract corpus: they are per build, already shaped like
# real queries, and cost nothing to maintain.
CASES_DIR = PGEO_ROOT.parent / "tests" / "accuracy"
PATHS = {"search": "search", "structured": "search/structured",
         "autocomplete": "autocomplete", "reverse": "reverse"}


async def parser_probes(build: str, limit: int = 60) -> list[tuple[str, dict]]:
    """Queries aimed at the decisions the two parsers make differently.

    The accuracy set is not enough on its own, and that was measured rather than assumed: with
    the state-aware typo fallback removed from one front end, a 198-case sample of Texas plus
    Louisiana plus Arkansas still reported agreement, because only six of its cases pair a typo
    with a state and all six are addresses that name the city too. The path that actually drifted
    - a misspelled town, with a state, and no other clue - was never asked.

    So these are generated from the build's own towns: the ambiguous ones first, since a name in
    two states is where the state has to be consulted at all.
    """
    import asyncpg

    from pgeo.regions import stack_env

    # A build other than the default has its own database on its own port; without this the
    # probes come from whichever build is the default and say nothing about this one.
    for key, value in stack_env(build).items():
        os.environ.setdefault(key, value)   # an explicit PGEO_DSN still wins, as in pgeo-load
    con = await asyncpg.connect(Settings.load().dsn, timeout=30)
    try:
        rows = await con.fetch(
            """SELECT name, array_agg(DISTINCT region_a) AS states
               FROM pgeo.town WHERE region_a IS NOT NULL AND length(name) >= 6
               GROUP BY name
               ORDER BY count(DISTINCT region_a) DESC, name
               LIMIT $1""",
            limit,
        )
    finally:
        await con.close()

    def typo(name: str) -> str:
        """One transposition in the middle - the commonest real typo, and the case the fallback
        treats specially."""
        i = len(name) // 2
        return name[:i] + name[i + 1] + name[i] + name[i + 2:] if i + 2 <= len(name) else name

    probes: list[tuple[str, dict]] = []
    for r in rows:
        name, states = r["name"], list(r["states"])
        probes.append(("search", {"text": name}))
        for st in states:
            probes.append(("search", {"text": f"{name}, {st}"}))
            probes.append(("search", {"text": f"{typo(name)}, {st}"}))
    return probes


def shape_probes() -> list[tuple[str, dict]]:
    """Queries chosen for their *shape* rather than their text.

    The accuracy cases and the parser probes are all well-formed free-text searches, which is why
    neither caught a structured query carrying no address at all: the SQL front end read a plpgsql
    record it had only assigned on the address branch and raised 55000, while FastAPI answered
    normally. Every case below leaves out something a caller is allowed to leave out.

    The place names are Maine's and are not looked up in the build: what is being compared is that
    both front ends do the same thing with the same shape, and two empty answers agree just as
    well as two matching ones.
    """
    return [
        # structured, in the subsets Pelias accepts - the address is optional in all of them
        ("search/structured", {"locality": "Portland", "region": "ME"}),
        ("search/structured", {"locality": "Portland"}),
        ("search/structured", {"region": "ME"}),
        ("search/structured", {"county": "Penobscot"}),
        ("search/structured", {"postalcode": "04401"}),
        ("search/structured", {"address": "100 Broad St", "locality": "Bangor"}),
        ("search/structured", {"address": "Broad St", "locality": "Bangor"}),
        ("search/structured", {"neighbourhood": "Bangor", "region": "ME"}),
        # free text carrying nothing but a filter
        ("search", {"text": "Bangor", "layers": "locality"}),
        ("search", {"text": "Bangor", "sources": "whosonfirst"}),
        ("autocomplete", {"text": "Bango", "layers": "locality"}),
        ("reverse", {"point.lat": 44.8, "point.lon": -68.77, "layers": "address"}),
    ]


def _installed_version() -> str | None:
    """The pgeo being tested. None when it cannot be determined, which disables the comparison
    rather than failing every check."""
    from importlib.metadata import PackageNotFoundError, version

    try:
        return version("pgeo")
    except PackageNotFoundError:
        return None


def contract_cases(build: str, n: int) -> list[tuple[str, dict]]:
    """A sample of this build's accuracy queries, as (path, params). Seeded, so a disagreement
    found on one run can be reproduced on the next."""
    f = CASES_DIR / ("cases.json" if build == "me" else f"cases_{build}.json")
    if not f.exists():
        raise SystemExit(
            f"no case set for build {build!r}: {f.relative_to(PGEO_ROOT.parent)} is missing. "
            f"Build one with tests/accuracy/build_cases.py --build {build}"
        )
    cases = json.loads(f.read_text())
    # Seeded on purpose and not security-relevant: the sample has to be the same on every run,
    # or a disagreement found today cannot be reproduced tomorrow.
    rng = random.Random(20260925)  # noqa: S311
    if 0 < n < len(cases):
        cases = rng.sample(cases, n)
    return [(PATHS.get(c["endpoint"], c["endpoint"]), c["params"]) for c in cases]


def cmd_contract(args: argparse.Namespace) -> int:
    """Put the same queries through both front ends and fail on any disagreement.

    The two are separate implementations of one contract - FastAPI parses in Python and carries
    its parser in the container image, the pure-SQL edge parses in PL/pgSQL and carries it in the
    database - so they drift, and they have: a fix applied to one parser and not the other sent
    "Hosuton, TX" to Houston on one and to Hosston, Louisiana on the other, and before that a
    container left on an older image served a parser the database had already replaced. Nothing
    reported either; the known answers matched on a substring and passed.

    The corpus is this build's accuracy cases plus queries generated from its own towns to hit
    the places the parsers decide things - see parser_probes, and the measurement there for why
    the accuracy cases alone were not enough.

    Compared on the top result's gid, which is the identity of the answer rather than its
    presentation. An empty answer from both is agreement: the contract is that they behave alike,
    not that they always find something.
    """
    import httpx

    api, sql = args.api.rstrip("/"), args.sql.rstrip("/")
    cases = (contract_cases(args.build, args.n) + shape_probes()
             + asyncio.run(parser_probes(args.build)))
    disagreements = []
    for path, params in cases:
        answers = []
        for base in (api, sql):
            try:
                r = httpx.get(f"{base}/v1/{path}", params=params | {"size": 1}, timeout=20)
                feats = r.json().get("features", []) if r.status_code == 200 else None
                if feats is None:
                    answers.append(f"<HTTP {r.status_code}>")
                else:
                    answers.append(feats[0]["properties"].get("gid", "?") if feats else "<none>")
            except (httpx.HTTPError, ValueError) as e:
                answers.append(f"<error {type(e).__name__}>")
        if answers[0] != answers[1]:
            disagreements.append((path, params, answers[0], answers[1]))

    for path, params, a, b in disagreements[:20]:
        print(f"DIFFER {path} {params}\n         fastapi {a}\n         sql     {b}")
    n = len(cases)
    if disagreements:
        print(f"contract: {len(disagreements)} of {n} queries disagree between the two front ends")
        return 1
    print(f"contract: {n} queries, both front ends agree")
    return 0


def cmd_verify(args: argparse.Namespace) -> int:
    import httpx

    failures = 0
    cases = verify_cases(args.build)
    for base in args.url:
        for path, params, want, want_layer in cases:
            layer = ""
            try:
                r = httpx.get(f"{base.rstrip('/')}/v1/{path}", params=params | {"size": 1}, timeout=10)
                feats = r.json().get("features", []) if r.status_code == 200 else []
                props = feats[0]["properties"] if feats else {}
                label = props.get("label", "") if feats else f"<HTTP {r.status_code}, no result>"
                layer = props.get("layer", "") or ""
            except (httpx.HTTPError, ValueError) as e:
                label = f"<error {type(e).__name__}>"
            ok = want in label and (want_layer is None or layer == want_layer)
            failures += not ok
            shown = f"{label}" + (f"  [{layer}]" if layer else "")
            if not ok and want_layer is not None and want in label and layer != want_layer:
                shown += f"  <- wanted layer {want_layer}"
            print(f"{'ok  ' if ok else 'FAIL'} {base} {path} {params} -> {shown}")
    # The version each front end reports has to be the one being tested, and the two get it from
    # different places: FastAPI from the package inside its container image, the pure-SQL edge
    # from geocode.engine_version() stamped into the database. Either can be left behind - an
    # image not rebuilt, or functions not re-applied - and three times in this project a stack
    # served new behaviour while reporting an old version, each time noticed by chance rather
    # than by a check. An unstamped database reports "0+unknown" and fails here too.
    expect = args.expect or None   # --expect '' accepts any well-formed version
    for base in args.url:
        name = ""
        try:
            # any query from this build's own set: only the stamped version is being read
            probe = cases[0][1] | {"size": 1}
            r = httpx.get(f"{base.rstrip('/')}/v1/{cases[0][0]}", params=probe, timeout=10)
            engine = (r.json().get("geocoding", {}).get("engine", {}) or {})
            ver, name = engine.get("version", ""), engine.get("name", "")
        except (httpx.HTTPError, ValueError) as e:
            ver = f"<error {type(e).__name__}>"
        shaped = bool(re.fullmatch(r"\d+\.\d+\.\d+", str(ver)))
        ok = shaped and (expect is None or ver == expect)
        failures += not ok
        note = ""
        if not shaped:
            note = "  (run pgeo-load build, or re-stamp geocode.engine_version())"
        elif not ok:
            # the two are behind for different reasons, so say which one applies
            fix = ("rebuild this build's api image: docker compose ... build api && ... up -d api"
                   if name == "pgeo" else
                   "re-apply the functions: pgeo-load functions --build <build>")
            note = f"  != {expect} being tested\n       {fix}"
        print(f"{'ok  ' if ok else 'FAIL'} {base} engine version -> {ver}{note}")
    print("verify:", "passed" if not failures else f"{failures} failure(s)")
    return 1 if failures else 0


def main() -> None:
    ap = argparse.ArgumentParser(prog="pgeo-tune", description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list").set_defaults(fn=cmd_list)
    a = sub.add_parser("apply")
    a.add_argument("profile")
    a.add_argument("--no-restart", action="store_true")
    a.add_argument("-f", "--file", type=Path, action="append", default=[], help="extra compose file")
    a.set_defaults(fn=cmd_apply)
    au = sub.add_parser("auto")
    au.add_argument("--cpus", type=int, required=True)
    au.add_argument("--mem-gb", type=float, required=True)
    au.add_argument("--write", action="store_true", help="save as profiles/auto.toml")
    au.set_defaults(fn=cmd_auto)
    sub.add_parser("show").set_defaults(fn=cmd_show)
    v = sub.add_parser("verify")
    v.add_argument("--url", action="append", default=None)
    v.add_argument("--build", default="me", help="which known-answer set to use")
    v.add_argument("--expect", default=_installed_version(),
                   help="engine version both front ends must report (default: the installed "
                        "pgeo; pass an empty string to accept any well-formed version)")
    v.set_defaults(fn=cmd_verify)
    c = sub.add_parser("contract", help="the two front ends must answer alike")
    c.add_argument("--api", required=True, help="FastAPI base URL")
    c.add_argument("--sql", required=True, help="pure-SQL edge base URL")
    c.add_argument("--build", default="me", help="whose accuracy case set to sample")
    c.add_argument("--n", type=int, default=200, help="how many queries (0 = all)")
    c.set_defaults(fn=cmd_contract)
    args = ap.parse_args()
    if args.cmd == "verify" and not args.url:
        args.url = ["http://127.0.0.1:4500", "http://127.0.0.1:4700"]
    try:
        sys.exit(args.fn(args))
    except ProfileError as e:
        ap.exit(2, f"pgeo-tune: {e}\n")


if __name__ == "__main__":
    main()
