"""Run the capacity matrix against pgeo (PostgreSQL/PostGIS geocoder), same method as Pelias.

Same k6 session, SLOs, ramp and breaking rules as tests/load/run_matrix.py (imported, not
modified), so results are directly comparable in tests/load/report.py. Differences:

- Engines (HTTP front ends to the same database):
    rest     PostgREST + nginx path edge, all logic in SQL (Phase 13, pure SQL)
    api      FastAPI + asyncpg, rule parser (PGEO_PARSE_MODE=none)
    api-svc  FastAPI + libpostal service (PGEO_PARSE_MODE=service)
- Configurations set CPU count, container memory limits and a matching PostgreSQL memory
  profile (shared_buffers, effective_cache_size, work_mem) mounted as tuning/active.conf.
- Data volume (--datasets) is not part of this runner: pgeo subsets are separate builds
  (`pgeo-load build --sources ...`), run one build at a time with --label.

Usage (repo root, after the Pelias runs have finished so cores are free):
    python3 tests/load/run_matrix_pgeo.py [--engines rest,api] [--configs P1,P2,P4] [--quick]

Cores: stacks use physical cores 0..N-1 (same as Pelias); k6 stays on core 5 (CPUs 5,11).
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import threading
import time
from datetime import datetime
from pathlib import Path

import run_matrix as rm

ROOT = rm.ROOT
PGEO = ROOT / "pgeo"
SECRETS = PGEO / "pgeo.secrets"
EDGE_CONF = ROOT / "scripts" / "dev" / "nginx.pgeo-rest.conf"
EDGE_IMAGE = "nginx:1.29-alpine"
OS_RESERVE_GB = rm.OS_RESERVE_GB

ENGINES = {
    # url the load hits, compose services it needs, extra containers (not compose-managed)
    "rest": {"url": "http://127.0.0.1:4700", "services": ["db", "rest"], "edge": True},
    "api": {"url": "http://127.0.0.1:4500", "services": ["db", "api"], "parse": "none"},
    "api-svc": {"url": "http://127.0.0.1:4500", "services": ["db", "api", "libpostal"], "parse": "service"},
}
CONTAINER = {"db": "pgeo_db", "api": "pgeo_api", "rest": "pgeo_rest", "libpostal": "pgeo_libpostal"}
EDGE = "pgeo_rest_edge"

# cpus (None = unconstrained), db memory limit GB, PostgreSQL memory profile, connections.
# The database is ~0.7 GB on disk (feature 612 MB incl. indexes), so P1..P4 keep it all in
# the page cache; Pmin tests whether it still meets the SLOs when it does not.
CONFIGS = {
    "PM": {"cpus": None, "db_gb": None, "sb": "1GB", "ecs": "4GB", "wm": "32MB", "conns": 16},
    "Pmin": {"cpus": 1, "db_gb": 0.6, "sb": "128MB", "ecs": "384MB", "wm": "8MB", "conns": 4},
    "P1": {"cpus": 1, "db_gb": 1.0, "sb": "256MB", "ecs": "768MB", "wm": "16MB", "conns": 4},
    "P2": {"cpus": 2, "db_gb": 1.5, "sb": "384MB", "ecs": "1GB", "wm": "16MB", "conns": 6},
    "P4": {"cpus": 4, "db_gb": 2.0, "sb": "512MB", "ecs": "1536MB", "wm": "16MB", "conns": 10},
}
LIBPOSTAL_GB = 2.0  # same as the Pelias floor profile


def front_gb(engine: str, cfg: dict) -> float:
    """Memory limit for the HTTP front end (PostgREST is small; uvicorn grows per worker)."""
    if engine == "rest":
        return 0.25
    return 0.15 + 0.1 * workers(cfg)


def workers(cfg: dict) -> int:
    return cfg["cpus"] or 4


def budget_gb(engine: str, cfg: dict) -> float | None:
    if cfg["db_gb"] is None:
        return None
    extra = LIBPOSTAL_GB if engine == "api-svc" else 0.0
    return round(cfg["db_gb"] + front_gb(engine, cfg) + extra + OS_RESERVE_GB, 1)


def cpuset(cfg: dict) -> str | None:
    return None if cfg["cpus"] is None else ",".join(str(c) for c in range(cfg["cpus"]))


def write_tuning(cfg: dict, tuning_dir: Path) -> None:
    """A whole tuning directory per config, mounted in place of pgeo/docker/db/tuning: mounting a
    single file inside the read-only base directory fails when the file does not exist there."""
    tuning_dir.mkdir(parents=True, exist_ok=True)
    (tuning_dir / "active.conf").write_text(
        "# generated by tests/load/run_matrix_pgeo.py\n"
        f"shared_buffers = {cfg['sb']}\n"
        f"effective_cache_size = {cfg['ecs']}\n"
        f"work_mem = {cfg['wm']}\n"
        "max_parallel_workers_per_gather = 0\n"
    )


def write_override(engine: str, cfg: dict, path: Path, tuning: Path) -> None:
    eng = ENGINES[engine]
    cs = cpuset(cfg)
    lines = ["services:"]
    for svc in eng["services"]:
        lines.append(f"  {svc}:")
        # compose.yml does not pin; the dev pin (compose.pinned.yml) is not loaded here
        if cs:
            lines.append(f'    cpuset: "{cs}"')
        limit = None
        if svc == "db":
            limit = cfg["db_gb"]
            lines += ["    volumes:", f'      - "{tuning}:/etc/postgresql/tuning:ro"']
        elif svc in ("api", "rest") and cfg["db_gb"] is not None:
            limit = front_gb(engine, cfg)
        elif svc == "libpostal" and cfg["db_gb"] is not None:
            limit = LIBPOSTAL_GB
        if limit:
            mb = int(limit * 1024)
            lines += [f"    mem_limit: {mb}m", f"    memswap_limit: {mb}m"]
        if svc == "api":
            n = workers(cfg)
            pool = max(2, cfg["conns"] // n)
            lines += [
                "    environment:",
                f'      PGEO_PARSE_MODE: "{eng["parse"]}"',
                f'      PGEO_WORKERS: "{n}"',
                f'      PGEO_POOL_MAX: "{pool}"',
            ]
        if svc == "rest":
            lines += ["    environment:", f'      PGRST_DB_POOL: "{cfg["conns"]}"']
    path.write_text("\n".join(lines) + "\n")


def compose(files: list[Path], *args: str) -> None:
    cmd = ["docker", "compose", "--env-file", str(SECRETS)]
    for f in files:
        cmd += ["-f", str(f)]
    rm.sh(cmd + list(args), env=rm.env(), cwd=ROOT)


def stop_all() -> None:
    subprocess.run(["docker", "stop", *CONTAINER.values(), EDGE], capture_output=True)


def start_edge(cs: str | None) -> None:
    subprocess.run(["docker", "rm", "-f", EDGE], capture_output=True)
    cmd = ["docker", "run", "-d", "--name", EDGE, "--restart", "unless-stopped", "--network", "host"]
    if cs:
        cmd += ["--cpuset-cpus", cs]
    cmd += ["-v", f"{EDGE_CONF}:/etc/nginx/conf.d/default.conf:ro", EDGE_IMAGE]
    rm.sh(cmd)


def names(engine: str) -> list[str]:
    out = [CONTAINER[s] for s in ENGINES[engine]["services"]]
    return out + ([EDGE] if ENGINES[engine].get("edge") else [])


def health(engine: str) -> dict:
    out = {}
    for name in names(engine):
        r = subprocess.run(
            ["docker", "inspect", "-f", "{{.State.Status}} {{.State.OOMKilled}} {{.RestartCount}}", name],
            text=True,
            capture_output=True,
        )
        status, oom, restarts = (r.stdout.split() + ["?", "?", "?"])[:3]
        out[name.removeprefix("pgeo_")] = {
            "status": status,
            "oom": oom == "true",
            "restarts": int(restarts) if restarts.isdigit() else -1,
        }
    return out


class Sampler(threading.Thread):
    """docker stats every ~2 s for the engine's containers (same format as run_matrix)."""

    def __init__(self, engine: str) -> None:
        super().__init__(daemon=True)
        self.names = names(engine)
        self.samples: list[dict] = []
        self._stop = threading.Event()

    def run(self) -> None:
        while not self._stop.is_set():
            r = subprocess.run(
                ["docker", "stats", "--no-stream", "--format", "{{.Name}}|{{.CPUPerc}}|{{.MemUsage}}", *self.names],
                text=True,
                capture_output=True,
            )
            t = time.time()
            for line in r.stdout.splitlines():
                name, cpu, mem = line.split("|")
                used = mem.split("/")[0].strip()
                num = float(used[:-3]) if used[-3:] in ("GiB", "MiB", "KiB") else 0.0
                mb = num * {"GiB": 1024, "MiB": 1, "KiB": 1 / 1024}.get(used[-3:], 0)
                self.samples.append(
                    {"t": t, "svc": name.removeprefix("pgeo_"), "cpu": float(cpu.rstrip("%") or 0), "mem_mb": mb}
                )
            self._stop.wait(2)

    def stop(self) -> None:
        self._stop.set()
        self.join(timeout=10)


def summarize(engine: str, samples: list[dict]) -> dict:
    # run_matrix.summarize_resources keys on its SERVICES list; reuse it with ours.
    saved = rm.SERVICES
    rm.SERVICES = [n.removeprefix("pgeo_") for n in names(engine)]
    try:
        return rm.summarize_resources(samples)
    finally:
        rm.SERVICES = saved


def db_size_mb() -> int:
    r = rm.sh(["docker", "exec", "pgeo_db", "psql", "-U", "pgeo", "-d", "pgeo", "-Atc",
               "SELECT pg_database_size('pgeo')"])  # fmt: skip
    return round(int(r.stdout.strip()) / 1048576)


def feature_count() -> int:
    r = rm.sh(["docker", "exec", "pgeo_db", "psql", "-U", "pgeo", "-d", "pgeo", "-Atc",
               "SELECT count(*) FROM pgeo.feature"])  # fmt: skip
    return int(r.stdout.strip())


def died(h: dict) -> bool:
    return any(x["status"] != "running" or x["oom"] or x["restarts"] > 0 for x in h.values())


def run_config(engine: str, cid: str, cfg: dict, out_dir: Path, quick: bool, label: str | None) -> dict:
    rid = f"{engine}-{cid}" + (f"-{label}" if label else "")
    print(f"\n=== {rid} {cfg}", flush=True)
    rm.API = ENGINES[engine]["url"]  # run_k6 and wait_ready read this module global
    tuning = out_dir / f"tuning-{cid}"
    override = out_dir / f"override-{rid}.yml"
    write_tuning(cfg, tuning)
    write_override(engine, cfg, override, tuning)
    stop_all()
    compose([PGEO / "compose.yml", override], "up", "-d", "--force-recreate", "--no-deps", *ENGINES[engine]["services"])
    if ENGINES[engine].get("edge"):
        start_edge(cpuset(cfg))
    rm.wait_ready()
    rm.run_k6(2, "30s", "5s", out_dir / rid / "warmup.json")  # warm caches, not recorded
    result = {
        "id": rid,
        "engine": f"pgeo-{engine}",
        "base_config": cid,
        "dataset": label,
        "docs": feature_count(),
        "index_mb": db_size_mb(),
        "config": cfg | {"engine": engine},
        "budget_gb": budget_gb(engine, cfg),
        "runs": {},
    }

    val_dur, val_warm = ("60s", "15s") if quick else ("180s", "45s")
    s = Sampler(engine)
    s.start()
    summ = rm.run_k6(3, val_dur, val_warm, out_dir / rid / "validate-3.json")
    s.stop()
    h = health(engine)
    v = rm.evaluate(summ) | {"resources": summarize(engine, s.samples), "health": h, "died": died(h)}
    v["pass"] = v["pass"] and not v["died"]
    result["runs"]["validate"] = v
    print(
        f"  validate@3: pass={v['pass']} err={v['error_rate']} worst={v['worst_p95_ratio']} "
        f"rps={v['req_rate']} stack_cpu_p95={v['resources'].get('_stack', {}).get('cpu_p95')}",
        flush=True,
    )

    ramp: list[dict] = []
    limit = 0
    step_dur, step_warm = ("30s", "10s") if quick else ("60s", "15s")
    for n in rm.RAMP:
        s = Sampler(engine)
        s.start()
        summ = rm.run_k6(n, step_dur, step_warm, out_dir / rid / f"ramp-{n:03d}.json")
        s.stop()
        e = rm.evaluate(summ)
        h = health(engine)
        step = e | {"vus": n, "resources": summarize(engine, s.samples), "health": h, "died": died(h)}
        ramp.append(step)
        if e["pass"]:
            limit = n
        print(
            f"  ramp@{n}: pass={e['pass']} err={e['error_rate']} worst={e['worst_p95_ratio']} "
            f"rps={e['req_rate']} stack_cpu_p95={step['resources'].get('_stack', {}).get('cpu_p95')}"
            f"{' DIED' if step['died'] else ''}",
            flush=True,
        )
        if step["died"] or e["broken"]:
            break
    result["runs"]["ramp"] = ramp
    result["limit_users"] = limit
    result["breaking_users"] = ramp[-1]["vus"] if ramp and (ramp[-1]["broken"] or ramp[-1]["died"]) else None
    (out_dir / f"{rid}.json").write_text(json.dumps(result, indent=1))
    return result


def restore() -> None:
    """Back to the development layout: all services pinned to cores 4,10 (compose.pinned.yml)."""
    compose([PGEO / "compose.yml", PGEO / "compose.pinned.yml"], "up", "-d", "--force-recreate")
    start_edge("4,10")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--engines", default="rest,api")
    ap.add_argument("--configs", default="Pmin,P1,P2,P4,PM")
    ap.add_argument("--label", default=None, help="data-volume label (e.g. D3) for a subset build")
    ap.add_argument("--quick", action="store_true", help="short windows, for trying the harness")
    ap.add_argument("--no-restore", action="store_true")
    args = ap.parse_args()
    for e in args.engines.split(","):
        if e not in ENGINES:
            ap.error(f"unknown engine {e}")
    for c in args.configs.split(","):
        if c not in CONFIGS:
            ap.error(f"unknown config {c}")
    run_id = datetime.now().strftime("%Y%m%d-%H%M") + "-pgeo"
    out_dir = ROOT / "data" / "loadtest" / run_id
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"run {run_id} -> {out_dir}", flush=True)
    try:
        for e in args.engines.split(","):
            for c in args.configs.split(","):
                run_config(e, c, CONFIGS[c], out_dir, args.quick, args.label)
    finally:
        if not args.no_restore:
            print("restoring the development layout", flush=True)
            restore()
    print(f"done: {out_dir}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
