#!/usr/bin/env bash
# First-time setup of pgeo on a workstation: secrets, images, database, API front ends, edge.
# Idempotent: an existing pgeo/pgeo.secrets is kept, images are rebuilt only when changed.
#
#   scripts/pgeo_setup.sh [--profile workstation] [--no-pin]
#
# Afterwards build the database and apply all tuning with scripts/pgeo_rebuild.sh.
# Requires: docker (compose v2), uv. Reads no data; the build does (docs/REBUILD.md).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

profile=workstation
pin=1
while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) profile="${2:?}"; shift 2 ;;
    --no-pin) pin=0; shift ;;
    -h|--help) sed -n '2,8p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

secrets=pgeo/pgeo.secrets
if [[ ! -f "$secrets" ]]; then
  echo "== creating $secrets (random passwords; mode 600; never committed)"
  rand() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48; }
  umask 077
  {
    echo "# pgeo local secrets (generated by scripts/pgeo_setup.sh). Never commit."
    echo "PGEO_DB_PASSWORD=$(rand)"
    echo "PGEO_API_PASSWORD=$(rand)"
    echo "PGEO_DATA_DIR=$ROOT/data/pgeo"
    echo "PGEO_PARSE_MODE=none"
    echo "DOCKER_USER=$(id -u):$(id -g)"
  } > "$secrets"
  umask 022
fi
mkdir -p data/pgeo/pgdata data/pgeo/stage data/pgeo/dumps

files=(-f pgeo/compose.yml)
[[ $pin -eq 1 ]] && files+=(-f pgeo/compose.pinned.yml)   # keep pgeo off the load-test cores

echo "== building images (the database image compiles libpostal once; later runs use the cache)"
docker compose --env-file "$secrets" "${files[@]}" build db api

echo "== tuning profile '$profile' and start (database, PostgREST, FastAPI)"
# No health check yet: there is no geocoder database before the first build
# (scripts/pgeo_rebuild.sh applies the profile again and verifies everything).
uv run --project pgeo pgeo-tune apply "$profile" --no-restart
docker compose --env-file "$secrets" --env-file pgeo/tuning/active.vars "${files[@]}" up -d db api rest

echo "== pure-SQL edge on 127.0.0.1:4700 (Pelias paths -> PostgREST)"
docker rm -f pgeo_rest_edge >/dev/null 2>&1 || true
cpus=(); [[ $pin -eq 1 ]] && cpus=(--cpuset-cpus 4,10)
docker run -d --name pgeo_rest_edge --restart unless-stopped --network host "${cpus[@]}" \
  -v "$ROOT/scripts/dev/nginx.pgeo-rest.conf:/etc/nginx/conf.d/default.conf:ro" nginx:1.29-alpine >/dev/null

echo "pgeo is set up. Next: scripts/pgeo_rebuild.sh --profile $profile$([[ $pin -eq 1 ]] && echo ' -f pgeo/compose.pinned.yml')"
