#!/usr/bin/env bash
# First-time setup of pgeo on a workstation: secrets, images, database, API front ends, edge.
# Idempotent: an existing pgeo/pgeo.secrets is kept, images are rebuilt only when changed.
#
#   scripts/pgeo_setup.sh [--profile workstation] [--no-pin] [--build NAME] [--offset N]
#
# One stack serves one build (one set of states, regions/regions.json). The default build is
# "me" and keeps the original names, ports and data directory. Any other build gets its own
# stack beside it, N steps up the port range (default offset 1):
#
#   scripts/pgeo_setup.sh --build ny          # pgeo-ny_db on 5434, API 4501, REST 4601, SQL 4701
#
# Afterwards build the database and apply all tuning with scripts/pgeo_rebuild.sh --build NAME.
# Requires: docker (compose v2), uv. Reads no data; the build does (docs/REBUILD.md).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

profile=workstation
pin=1
build=me
offset=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) profile="${2:?}"; shift 2 ;;
    --build) build="${2:?}"; shift 2 ;;
    --offset) offset="${2:?}"; shift 2 ;;
    --no-pin) pin=0; shift ;;
    -h|--help) sed -n '2,13p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
# A build given as a state list ("me,nh,vt") names a directory, a database and containers, so
# it takes the same dashed form the rest of the pipeline uses.
build="$(tr ',' '-' <<<"${build,,}")"
[[ -n "$offset" ]] || { [[ "$build" == "me" ]] && offset=0 || offset=1; }
[[ "$offset" =~ ^[0-9]+$ ]] || { echo "--offset must be a number" >&2; exit 2; }

secrets=pgeo/pgeo.secrets
if [[ ! -f "$secrets" ]]; then
  echo "== creating $secrets (random passwords; mode 600; never committed)"
  rand() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48; }
  umask 077
  {
    echo "# pgeo local secrets (generated by scripts/pgeo_setup.sh). Never commit."
    echo "PGEO_DB_PASSWORD=$(rand)"
    echo "PGEO_API_PASSWORD=$(rand)"
    echo "PGEO_DATA_DIR=$ROOT/data/pgeo"
    echo "PGEO_PARSE_MODE=none"
    echo "DOCKER_USER=$(id -u):$(id -g)"
  } > "$secrets"
  umask 022
fi
# The data directory is recorded as an absolute path when the secrets file is first written, so
# renaming the checkout leaves it pointing at a directory that no longer exists. Running
# containers survive on the open inode and look fine; the next `up --force-recreate` would let
# Docker create the missing path and PostgreSQL initialise an empty cluster there. Caught after
# the checkout was renamed from pelia_maine to pgeo, with the Maine stack still mounted on the
# old name. Only a path that has gone missing is corrected, since pointing the data at another
# disk is a legitimate thing to do.
recorded="$(sed -n 's/^PGEO_DATA_DIR=//p' "$secrets" | tail -1)"
if [[ -n "$recorded" && ! -d "$recorded" ]]; then
  moved="$ROOT/data/$(basename "$recorded")"
  if [[ -d "$moved" ]]; then
    echo "== PGEO_DATA_DIR pointed at $recorded, which is gone; using $moved"
    sed -i "s|^PGEO_DATA_DIR=.*|PGEO_DATA_DIR=${moved}|" "$secrets"
  else
    echo "PGEO_DATA_DIR=$recorded does not exist and there is no $moved to use instead" >&2
    exit 1
  fi
fi

# Names, ports and paths for this build. Offset 0 reproduces the original single-stack layout
# exactly, so the Maine stack is untouched by the arrival of a second build.
stack=pgeo; data_dir="$ROOT/data/pgeo"; env_files=(--env-file "$secrets")
db_port=$((5433 + offset)); api_port=$((4500 + offset))
rest_port=$((4600 + offset)); sql_port=$((4700 + offset)); lp_port=$((4401 + offset))
if [[ "$build" != "me" ]]; then
  stack="pgeo-${build}"; data_dir="$ROOT/data/pgeo-${build}"
  mkdir -p pgeo/builds
  umask 077
  cat > "pgeo/builds/${build}.env" <<EOF
# Generated by scripts/pgeo_setup.sh --build ${build} --offset ${offset}. Not committed.
# Passed to docker compose after pgeo/pgeo.secrets, which holds the passwords:
#   docker compose --env-file pgeo/pgeo.secrets --env-file pgeo/builds/${build}.env \\
#     -f pgeo/compose.yml up -d
PGEO_BUILD=${build}
PGEO_STACK=${stack}
PGEO_DB_NAME=pgeo_${build}
PGEO_DB_PORT=${db_port}
PGEO_LIBPOSTAL_PORT=${lp_port}
PGEO_API_PORT=${api_port}
PGEO_REST_PORT=${rest_port}
PGEO_DATA_DIR=${data_dir}
EOF
  umask 022
  env_files+=(--env-file "pgeo/builds/${build}.env")
  echo "== build ${build}: stack ${stack}, database pgeo_${build}, ports ${db_port}/${api_port}/${rest_port}/${sql_port}"
fi
mkdir -p "$data_dir/pgdata" "$data_dir/stage" "$data_dir/dumps"

files=(-f pgeo/compose.yml)
[[ $pin -eq 1 ]] && files+=(-f pgeo/compose.pinned.yml)   # keep pgeo off the load-test cores

echo "== building images (the database image compiles libpostal once; later runs use the cache)"
docker compose "${env_files[@]}" "${files[@]}" build db api

echo "== tuning profile '$profile' and start (database, PostgREST, FastAPI)"
# No health check yet: there is no geocoder database before the first build
# (scripts/pgeo_rebuild.sh applies the profile again and verifies everything).
#
# Server tuning is per workstation, not per stack: every stack mounts the same
# pgeo/docker/db/tuning directory and reads the same pgeo/tuning/active.vars. So a second build
# does not get its own profile here, and applying one would move the first build's settings too.
# On a host that serves one build - the VPS case, and the container images - this does not arise.
if [[ "$build" != "me" && -f pgeo/tuning/active.vars ]]; then
  echo "   keeping the active profile ($(sed -n 's/^PGEO_TUNING_PROFILE=//p' pgeo/tuning/active.vars)): it is shared with the other stacks on this machine"
else
  uv run --project pgeo pgeo-tune apply "$profile" --no-restart
fi
docker compose "${env_files[@]}" --env-file pgeo/tuning/active.vars "${files[@]}" up -d db api rest

echo "== pure-SQL edge on 127.0.0.1:${sql_port} (Pelias paths -> PostgREST)"
conf="$ROOT/scripts/dev/nginx.pgeo-rest.conf"
if [[ "$build" != "me" ]]; then
  # Same rules, this build's two ports.
  conf="$ROOT/pgeo/builds/${build}-rest.conf"
  sed -e "s/127\.0\.0\.1:4700/127.0.0.1:${sql_port}/" \
      -e "s/127\.0\.0\.1:4600/127.0.0.1:${rest_port}/" \
      "$ROOT/scripts/dev/nginx.pgeo-rest.conf" > "$conf"
fi
docker rm -f "${stack}_rest_edge" >/dev/null 2>&1 || true
cpus=(); [[ $pin -eq 1 ]] && cpus=(--cpuset-cpus 4,10)
docker run -d --name "${stack}_rest_edge" --restart unless-stopped --network host "${cpus[@]}" \
  -v "$conf:/etc/nginx/conf.d/default.conf:ro" nginx:1.29-alpine >/dev/null

echo "pgeo is set up. Next: scripts/pgeo_rebuild.sh --build $build --profile $profile$([[ $pin -eq 1 ]] && echo ' -f pgeo/compose.pinned.yml')"
