#!/usr/bin/env bash
# Vendor the demo page's third-party assets into web/vendor/ (committed to git).
# The site CSP allows only same-origin scripts, styles, fonts and workers, so nothing may
# load from a CDN. Every npm tarball is checked against a pinned sha512 integrity value;
# GitHub assets come from a pinned commit.
#
# Usage: scripts/vendor_web.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDOR="${ROOT}/web/vendor"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# name@version|sha512 integrity (from `npm view <pkg>@<ver> dist.integrity`)
PACKAGES=(
  "maplibre-gl@6.10.0|sha512-pZIJ1/rsB1jDjT3eBTfMaeSY45lRKdCuZtqXqTnkUrn0UJO9IwtbywT5ym3/cz57MGEELwAwQSYjB/Fj9TlktQ=="
  "pmtiles@4.5.0|sha512-CBeD4SoUluFziGdy/8k7FOjQxQy486n+929W/tWophauvMICpkZ26vGBWhDt/6b1FZQWNaf4jFdT/5+q0Wii5w=="
  "@protomaps/basemaps@5.7.2|sha512-K1Yk6bWdULulYg+R2QRVXx4NzJZan5YQhpejEG0c1/sXruJrfPIPZuakpf3jwAgVmjIRVQwAv+yRafDeN0aaUQ=="
  "@fontsource/fraunces@5.3.0|sha512-LEHTOBiZufQzAvnAe2rZ8ZknbDS28Q9kzwb0L+gZJEmjLGr8hhZ/5NuHXwDuHBWhVXYoiGGXmrb0H6Ko/RrHTg=="
  "@fontsource/ibm-plex-sans-condensed@5.3.0|sha512-fQyBpwbkguP4azjq7Cw8h/J3C/d8MFAzXOiSoFxyKCUK4x0XKrWEh3tGdTxhDM0HctVRQilQo1zGoyxDHLm5jQ=="
  "@fontsource/ibm-plex-mono@5.3.0|sha512-eTgnZjZEGk1QtD3ZstF+Vclo2HLAni8YMy34/DxllwZvyz1lR/1RF/xTiAquOBO7MvqBx8D2Ig2WCPMVfdZu7Q=="
)
# Protomaps basemap glyphs and sprites (protomaps/basemaps-assets)
ASSETS_REF="028c18f713baecad011301ff7a69acc39bcc2ae7"
ASSETS_BASE="https://raw.githubusercontent.com/protomaps/basemaps-assets/${ASSETS_REF}"
FONTSTACKS=("Noto Sans Regular" "Noto Sans Medium" "Noto Sans Italic")
# Basic Latin + Latin-1, Latin Extended-A (Acadian/French names), general punctuation.
GLYPH_RANGES=("0-255" "256-511" "8192-8447")

fetch_pkg() {  # fetch_pkg name@version expected_integrity -> extracted dir path
  local spec="$1" expected="$2" tgz actual
  tgz="$(cd "$WORK" && npm pack --silent "$spec")"
  [[ -n "$expected" ]] || { echo "no pinned integrity for ${spec}" >&2; exit 1; }
  actual="sha512-$(openssl dgst -sha512 -binary "${WORK}/${tgz}" | base64 -w0)"
  if [[ "$actual" != "$expected" ]]; then
    echo "integrity mismatch for ${spec}" >&2
    exit 1
  fi
  mkdir -p "${WORK}/${tgz%.tgz}"
  tar xzf "${WORK}/${tgz}" -C "${WORK}/${tgz%.tgz}"
  echo "${WORK}/${tgz%.tgz}/package"
}

rm -rf "$VENDOR"
mkdir -p "${VENDOR}"/{maplibre-gl,pmtiles,basemaps,fonts,glyphs,sprites}
lock="${VENDOR}/VENDOR.lock"
echo "# Generated by scripts/vendor_web.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$lock"

for entry in "${PACKAGES[@]}"; do
  spec="${entry%%|*}" integrity="${entry#*|}"
  dir="$(fetch_pkg "$spec" "$integrity")"
  echo "${spec} ${integrity}" >> "$lock"
  case "$spec" in
    maplibre-gl@*)
      cp "${dir}"/dist/{maplibre-gl.mjs,maplibre-gl-shared.mjs,maplibre-gl-worker.mjs,maplibre-gl.css} \
        "${VENDOR}/maplibre-gl/"
      cp "${dir}/LICENSE.txt" "${VENDOR}/maplibre-gl/" 2>/dev/null || true ;;
    pmtiles@*)
      cp "${dir}/dist/pmtiles.js" "${VENDOR}/pmtiles/" ;;
    @protomaps/basemaps@*)
      cp "${dir}/dist/basemaps.js" "${VENDOR}/basemaps/" ;;
    @fontsource/*)
      cp "${dir}"/files/*-latin-{400,500,600}-{normal,italic}.woff2 "${VENDOR}/fonts/" 2>/dev/null || true
      cp "${dir}/LICENSE" "${VENDOR}/fonts/LICENSE-$(basename "${spec%@*}")" 2>/dev/null || true ;;
  esac
done

for stack in "${FONTSTACKS[@]}"; do
  mkdir -p "${VENDOR}/glyphs/${stack}"
  for range in "${GLYPH_RANGES[@]}"; do
    curl -fsSL -o "${VENDOR}/glyphs/${stack}/${range}.pbf" \
      "${ASSETS_BASE}/fonts/${stack// /%20}/${range}.pbf"
  done
done
for f in {light,dark}.json {light,dark}.png {light,dark}@2x.json {light,dark}@2x.png; do
  curl -fsSL -o "${VENDOR}/sprites/${f}" "${ASSETS_BASE}/sprites/v4/${f}"
done
echo "protomaps/basemaps-assets ${ASSETS_REF}" >> "$lock"

du -sh "$VENDOR"
echo "vendored into ${VENDOR}"
